name: PaidCommandPoints
version: 1.0.0
main: net.udgame.gdenga.paidcommandpoints.PaidCommandPoints
api-version: 1.13
depend: [PlayerPoints]
authors: [gdenga]
description: 付费指令-点券版
website: www.gdenga.top
commands:
  pcp:
    usage: /pcp help
permissions:
  pcp.admin:
    description: 付费指令操作权限
    default: op
  pcp.free:
    description: 免费全部付费指令权限
    default: op
